language: ruby
rvm:
  - 2.2.2
sudo: false
cache: bundler
script: "bundle exec rake $TASK"
env:
  matrix:
    - "TASK=bench TEMPLATE=simple MODE=compiled"
    - "TASK=bench TEMPLATE=simple MODE=parsing"
    - "TASK=bench TEMPLATE=simple MODE=tilt"
